services:
  elasticsearch-node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://root:admin@mongo:27017/test?authSource=admin
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
      - PORT=3000
    command: npm run start:dev
    networks:
      - elastic-network

  mongo:
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongo-data:/data/db
    networks:
      - elastic-network
    deploy:
      resources:
        limits:
          memory: 512M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - logger.level=warn
    ports:
      - '9200:9200'
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge

volumes:
  # DB dagi malumotlar o'chib ketmasligi uchun
  mongo-data:
  # Elasticsearch index ma'lumotlari ochib kermasligi uchun
  es-data:
    driver: local
